### ISSUE TITLE
Calling `ProgressBar.complete()` exhausts all available memory

### ISSUE THREAD

**Issue by neko-kai** [morgen-peschke/scala-progress-bar#13]
Simple example:
```scala
import peschke.console.progressbar.ProgressBar
import scala.concurrent.ExecutionContext.Implicits.global

object Test extends App {
  val pb = ProgressBar(totalCount = 20000)
  pb.complete()
  Thread.sleep(9000000)
}
```

Expected: Constant memory usage

Actual: Explosion 💥

**Comment by morgen-peschke** [comment]
I'm unable to reproduce this locally, can you provide more details about the memory settings, how you're running it, and why you have it sleep for 2.5 hours?

**Comment by neko-kai** [comment]
False alarm: the version of this library I found copypasted in our codebase had [this line](https://github.com/morgen-peschke/scala-progress-bar/blob/master/src/main/scala/peschke/console/progressbar/Command.scala#L39) changed from `.takeUntil` to `.takeWhile`. With dire consequences for my sanity.

**Comment by morgen-peschke** [comment]
Yep, that would do it. 

I'd highly recommend using [JitPack.io](https://jitpack.io/#morgen-peschke/scala-progress-bar) to avoid copy-paste errors. 

I just pushed version 1.4.0, which switches to using this instead of an SBT dependency internally, and it works really well. The first time `sbt update` is run for a particular version it'll probably timeout, as it needs to build the jar, but after that there doesn't seem to be a noticeable difference in speed between that and the other dependencies.
